[build]
    base = "Bored Bot - Netifly"
    command = "npm run build" # Command to build your app
    publish = "dist"          # Directory where your build files are located

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
